name: import_suggest
channels:
  - conda-forge        # numpy, tqdm, boto3, ipywidgets, pip
  - pytorch            # official PyTorch wheels
dependencies:
  # core runtime
  - python=3.10
  - pandas
  - pytorch=2.2.*          # CPU build; install a CUDA wheel separately if needed
  - numpy>=1.26,<2         # compatible with PyTorch 2.2
  - tqdm>=4.66
  - boto3>=1.34            # only required if you load checkpoints from S3
  - mysql-connector-python
  - beautifulsoup4 
  - selenium
  - webdriver-manager
  - undetected-chromedriver
  - unidecode

 # Jupyter and widgets (for rich tqdm bars in notebooks)
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
 
  # pip-only packages
  - pip>=23
  - pip:
      - sentence-transformers==4.1.0
